name: test-api-mitu-institute

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Customization of SHA up to 7 characters 
        run: echo "GITHUB_SHA_CUSTOMIZE=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/test-api-mitu-institute:${{ env.GITHUB_SHA_CUSTOMIZE }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/test-api-mitu-institute:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/test-api-mitu-institute:buildcache,mode=max

